import { useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import JSZip from "jszip";
import { createQpdfRunner } from "qpdf-run";
import { normalizeMatchValue, pdfBaseName, resolveFilename } from "./filenameMatching";

type Person = { row:number; name:string; password:string };
type Row = Person & { key:string; pdf?:File; status:"ready"|"missing_pdf"|"missing_password"|"duplicate"|"invalid_filename"; message?:string; manual?:boolean };
const clean = (v:unknown) => String(v ?? "").normalize("NFKC").trim();
const key = (v:unknown) => normalizeMatchValue(v);
const labels = { ready:"可以加密", missing_pdf:"找不到 PDF", missing_password:"缺少密碼", duplicate:"名稱重複", invalid_filename:"檔名無法辨識" };
function save(blob:Blob,name:string){ const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }

export default function EncryptionTab(){
  const pdfInput=useRef<HTMLInputElement>(null), excelInput=useRef<HTMLInputElement>(null);
  const [pdfs,setPdfs]=useState<File[]>([]), [people,setPeople]=useState<Person[]>([]), [rows,setRows]=useState<Row[]>([]);
  const [excelName,setExcelName]=useState(""), [error,setError]=useState(""), [busy,setBusy]=useState(false), [progress,setProgress]=useState("");
  const summary=useMemo(()=>({ready:rows.filter(r=>r.status==="ready").length,problem:rows.filter(r=>r.status!=="ready").length}),[rows]);

  function rebuild(nextPdfs=pdfs,nextPeople=people){
    const counts=new Map<string,number>(), map=new Map<string,File[]>(), bad:Array<{pdf:File;message:string}>=[];
    nextPeople.forEach(p=>counts.set(key(p.name),(counts.get(key(p.name))??0)+1));
    nextPdfs.forEach(pdf=>{ const found=resolveFilename(pdf.name,nextPeople.map(p=>p.name)); if(found.status==="matched"){const k=key(found.name);map.set(k,[...(map.get(k)??[]),pdf]);}else bad.push({pdf,message:found.status==="ambiguous"?`同時符合：${found.names.join("、")}`:"檔名找不到 Excel 姓名"}); });
    const built=nextPeople.map<Row>(p=>{const files=map.get(key(p.name))??[];let status:Row["status"]="ready";if(!p.password)status="missing_password";else if((counts.get(key(p.name))??0)>1||files.length>1)status="duplicate";else if(!files.length)status="missing_pdf";return{...p,key:`p-${p.row}`,pdf:files[0],status};});
    bad.forEach(({pdf,message},i)=>built.push({row:0,name:pdfBaseName(pdf.name),password:"",key:`u-${i}-${pdf.name}`,pdf,status:"invalid_filename",message})); setRows(built);
  }
  function takePdfs(list:FileList|null){const next=Array.from(list??[]).filter(f=>f.name.toLowerCase().endsWith(".pdf"));setPdfs(next);rebuild(next,people);setProgress("");}
  async function takeExcel(file?:File){if(!file)return;setExcelName(file.name);setError("");try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array"}), data=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[wb.SheetNames[0]],{header:1,raw:false,defval:""});const headers=(data[0]??[]).map(clean);const ni=headers.findIndex(h=>["姓名","名字","name"].some(x=>key(x)===key(h))),pi=headers.findIndex(h=>["密碼","密码","password","pdf密碼"].some(x=>key(x)===key(h)));if(ni<0||pi<0)throw new Error("Excel 第一列必須包含：姓名、密碼");const next=data.slice(1).map((r,i)=>({row:i+2,name:clean(r[ni]),password:clean(r[pi])})).filter(p=>p.name);setPeople(next);rebuild(pdfs,next);}catch(e){setPeople([]);setRows([]);setError(e instanceof Error?e.message:"Excel 讀取失敗");}}
  function remove(row:Row){if(!row.pdf||busy||!confirm(`確定移除「${row.pdf.name}」？`))return;const next=pdfs.filter(f=>f!==row.pdf);setPdfs(next);rebuild(next,people);}
  function assign(sourceKey:string,rowNo:number){setRows(current=>{const source=current.find(r=>r.key===sourceKey&&r.row===0),person=people.find(p=>p.row===rowNo),target=current.find(r=>r.row===rowNo);if(!source?.pdf||!person||target?.pdf)return current;const duplicate=people.filter(p=>key(p.name)===key(person.name)).length>1;return current.filter(r=>r.key!==sourceKey).map(r=>r.row===rowNo?{...r,...person,pdf:source.pdf,status:!person.password?"missing_password":duplicate?"duplicate":"ready",manual:true,message:undefined}:r);});}
  function template(){const ws=XLSX.utils.aoa_to_sheet([["姓名","密碼"],["Sierra","Si@2026-001"]]);ws["!cols"]=[{wch:20},{wch:24}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"加密名單");XLSX.writeFile(wb,"PDF加密名單範本.xlsx");}
  async function encrypt(){const ready=rows.filter(r=>r.status==="ready"&&r.pdf);if(!ready.length||summary.problem||busy)return;setBusy(true);let runner:Awaited<ReturnType<typeof createQpdfRunner>>|null=null;try{runner=await createQpdfRunner({workerUrl:new URL("qpdf-run/worker",import.meta.url).href,qpdfJsUrl:new URL("qpdf-run/qpdf.js",import.meta.url).href,wasmUrl:new URL("qpdf-run/qpdf.wasm",import.meta.url).href,timeoutMs:60000});const zip=new JSZip();for(let i=0;i<ready.length;i++){const r=ready[i];setProgress(`正在加密 ${i+1} / ${ready.length}：${r.pdf!.name}`);const out=await runner.runOne({input:new Uint8Array(await r.pdf!.arrayBuffer()),inputName:"input.pdf",outputName:"encrypted.pdf",args:["--encrypt",r.password, r.password,"256","--","input.pdf","encrypted.pdf"]});zip.file(r.pdf!.name,Uint8Array.from(out));}setProgress("正在整理下載檔…");save(await zip.generateAsync({type:"blob",compression:"DEFLATE"}),`加密PDF_${new Date().toISOString().slice(0,10)}.zip`);setProgress(`完成：${ready.length} 份 PDF 已各自加密並下載。`);}catch(e){setProgress(e instanceof Error?e.message:"加密失敗");}finally{await runner?.destroy();setBusy(false);}}
  return <><section className="workflow-card"><div className="section-head"><div><p className="eyebrow">PART ONE</p><h2>批次 PDF 加密</h2></div><span className="section-note">只加密，不寄信</span></div><div className="upload-grid"><button className="dropzone" onClick={()=>pdfInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();takePdfs(e.dataTransfer.files)}}><input ref={pdfInput} type="file" multiple accept=".pdf,application/pdf" onChange={e=>takePdfs(e.target.files)}/><span className="upload-icon">PDF</span><strong>上傳全部 PDF</strong><small>檔名需對應 Excel 姓名</small><em>{pdfs.length?`已選擇 ${pdfs.length} 份 PDF`:"拖曳或點擊選擇"}</em></button><button className="dropzone" onClick={()=>excelInput.current?.click()}><input ref={excelInput} type="file" accept=".xlsx,.xls" onChange={e=>void takeExcel(e.target.files?.[0])}/><span className="upload-icon excel">XLS</span><strong>上傳密碼 Excel</strong><small>只需「姓名、密碼」兩欄</small><em>{excelName||"點擊選擇"}</em></button></div><div className="template-row"><span>{error||"每一份 PDF 使用對應姓名的專屬密碼"}</span><button onClick={template}>下載 Excel 範本</button></div></section>
  {rows.length>0&&<section className="results-card"><div className="section-head"><div><p className="eyebrow">ENCRYPTION REVIEW</p><h2>加密配對結果</h2></div><div className="stats"><span><b>{rows.length}</b> 全部</span><span className="ok"><b>{summary.ready}</b> 可加密</span><span className="warn"><b>{summary.problem}</b> 需處理</span></div></div><div className="table-wrap"><table><thead><tr><th>姓名</th><th>PDF 檔案</th><th>密碼</th><th>狀態</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}><td><strong>{r.name}</strong>{r.row>0&&<small>Excel 第 {r.row} 列</small>}</td><td><div className="pdf-file-line"><span>{r.pdf?.name||"—"}</span>{r.pdf&&<button className="remove-pdf-button" onClick={()=>remove(r)}>移除 PDF</button>}</div>{r.status==="invalid_filename"&&<label className="manual-match"><span>不用重傳，手動指定員工</span><select defaultValue="" onChange={e=>assign(r.key,Number(e.target.value))}><option value="" disabled>選擇 Excel 員工…</option>{people.map(p=>{const used=rows.some(x=>x.row===p.row&&x.pdf);return <option key={p.row} value={p.row} disabled={used}>{p.name}{used?"（已有 PDF）":""}</option>})}</select></label>}</td><td>{r.password?"••••••••":"—"}</td><td><span className={`badge ${r.status}`}>{labels[r.status]}</span>{r.manual&&<small className="manual-message">已手動配對</small>}{r.message&&<small className="row-message">{r.message}</small>}</td></tr>)}</tbody></table></div><div className="send-panel"><div className="review-note"><strong>下載為一個 ZIP</strong><span>ZIP 內每份 PDF 仍有自己的密碼。</span></div><div><p>{progress||(summary.problem?"請先處理全部異常。":`共 ${summary.ready} 份等待加密`)}</p><button className="send-button" disabled={!!summary.problem||!summary.ready||busy} onClick={()=>void encrypt()}>{busy?"正在加密…":"加密並下載全部 PDF"}</button></div></div></section>}</>;
}
