import { useEffect, useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { normalizeMatchValue, pdfBaseName, resolveFilename } from "./filenameMatching";

type Person={row:number;name:string;email:string};
type Row=Person&{key:string;pdf?:File;status:"ready"|"missing_pdf"|"missing_email"|"duplicate"|"invalid_filename";message?:string;manual?:boolean};
const clean=(v:unknown)=>String(v??"").normalize("NFKC").trim();
const key=(v:unknown)=>normalizeMatchValue(v);
const labels={ready:"可以寄送",missing_pdf:"找不到 PDF",missing_email:"缺少 Email",duplicate:"名稱重複",invalid_filename:"檔名無法辨識"};

export default function SingleMailTab(){
 const pdfInput=useRef<HTMLInputElement>(null),excelInput=useRef<HTMLInputElement>(null);
 const [mailReady,setMailReady]=useState<boolean|null>(null),[pdfs,setPdfs]=useState<File[]>([]),[people,setPeople]=useState<Person[]>([]),[rows,setRows]=useState<Row[]>([]),[excelName,setExcelName]=useState(""),[error,setError]=useState("");
 const [subject,setSubject]=useState("【個人文件】{{name}} 您的加密 PDF 文件"),[body,setBody]=useState("{{name}} 您好：\n\n附件是您的加密 PDF 文件，請使用約定的密碼開啟。\n\n如有問題，請聯絡相關承辦人員。\n謝謝"),[preview,setPreview]=useState(false),[previewIndex,setPreviewIndex]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const summary=useMemo(()=>({ready:rows.filter(r=>r.status==="ready").length,problem:rows.filter(r=>r.status!=="ready").length}),[rows]);
 const previewRows=useMemo(()=>rows.filter(r=>r.status==="ready"&&r.pdf),[rows]),previewRow=previewRows[previewIndex];
 useEffect(()=>{fetch("/api/config").then(r=>r.json()).then(v=>setMailReady(Boolean(v.larkReady))).catch(()=>setMailReady(false));},[]);
 const render=(text:string,row:Row)=>text.replace(/{{\s*name\s*}}/gi,row.name).replace(/{{\s*email\s*}}/gi,row.email).replace(/{{\s*filename\s*}}/gi,row.pdf?.name||"");

 function rebuild(nextPdfs=pdfs,nextPeople=people){
  const counts=new Map<string,number>(),map=new Map<string,File[]>(),bad:Array<{pdf:File;message:string}>=[];
  nextPeople.forEach(p=>counts.set(key(p.name),(counts.get(key(p.name))??0)+1));
  nextPdfs.forEach(pdf=>{const found=resolveFilename(pdf.name,nextPeople.map(p=>p.name));if(found.status==="matched"){const k=key(found.name);map.set(k,[...(map.get(k)??[]),pdf]);}else bad.push({pdf,message:found.status==="ambiguous"?`同時符合：${found.names.join("、")}`:"檔名找不到 Excel 姓名"});});
  const built=nextPeople.map<Row>(p=>{const files=map.get(key(p.name))??[];let status:Row["status"]="ready";if(!p.email)status="missing_email";else if((counts.get(key(p.name))??0)>1||files.length>1)status="duplicate";else if(!files.length)status="missing_pdf";return{...p,key:`p-${p.row}`,pdf:files[0],status};});
  bad.forEach(({pdf,message},i)=>built.push({row:0,name:pdfBaseName(pdf.name),email:"",key:`u-${i}-${pdf.name}`,pdf,status:"invalid_filename",message}));setRows(built);setMessage("");
 }
 function takePdfs(list:FileList|null){const next=Array.from(list??[]).filter(f=>f.name.toLowerCase().endsWith(".pdf"));setPdfs(next);rebuild(next,people);}
 async function takeExcel(file?:File){if(!file)return;setExcelName(file.name);setError("");try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array"}),data=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[wb.SheetNames[0]],{header:1,raw:false,defval:""}),headers=(data[0]??[]).map(clean);const ni=headers.findIndex(h=>["姓名","名字","name","收件人"].some(x=>key(x)===key(h))),ei=headers.findIndex(h=>["email","e-mail","mail","信箱","郵箱","收件信箱"].some(x=>key(x)===key(h)));if(ni<0||ei<0)throw new Error("Excel 第一列必須包含：姓名、Email");const next=data.slice(1).map((r,i)=>({row:i+2,name:clean(r[ni]),email:clean(r[ei])})).filter(p=>p.name);setPeople(next);rebuild(pdfs,next);}catch(e){setPeople([]);setRows([]);setError(e instanceof Error?e.message:"Excel 讀取失敗");}}
 function remove(row:Row){if(!row.pdf||busy||!confirm(`確定移除「${row.pdf.name}」？`))return;const next=pdfs.filter(f=>f!==row.pdf);setPdfs(next);rebuild(next,people);}
 function assign(sourceKey:string,rowNo:number){setRows(current=>{const source=current.find(r=>r.key===sourceKey&&r.row===0),person=people.find(p=>p.row===rowNo),target=current.find(r=>r.row===rowNo);if(!source?.pdf||!person||target?.pdf)return current;const duplicate=people.filter(p=>key(p.name)===key(person.name)).length>1;return current.filter(r=>r.key!==sourceKey).map(r=>r.row===rowNo?{...r,...person,pdf:source.pdf,status:!person.email?"missing_email":duplicate?"duplicate":"ready",manual:true,message:undefined}:r);});}
 function template(){const ws=XLSX.utils.aoa_to_sheet([["姓名","Email"],["Sierra","sierra@example.com"]]);ws["!cols"]=[{wch:20},{wch:30}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"寄送名單");XLSX.writeFile(wb,"PDF寄送名單範本.xlsx");}
 function openPreview(){if(summary.problem||!previewRows.length)return;setPreviewIndex(0);setPreview(true);}
 async function send(){if(!previewRows.length||busy)return;setPreview(false);setBusy(true);try{setMessage("正在建立批次寄送任務…");const cr=await fetch("/api/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject,body,items:previewRows.map(r=>({name:r.name,email:r.email,filename:r.pdf!.name}))})});const created=await cr.json();if(!cr.ok||!created.jobId||!created.items)throw new Error(created.error||"建立任務失敗");const ids=new Map<string,string>(created.items.map((x:{filename:string;itemId:string})=>[x.filename,x.itemId]));for(let i=0;i<previewRows.length;i++){const row=previewRows[i];setMessage(`正在上傳 ${i+1} / ${previewRows.length}：${row.pdf!.name}`);const id=ids.get(row.pdf!.name);if(!id)throw new Error("找不到寄送項目");const up=await fetch(`/api/jobs/${created.jobId}/items/${id}/upload`,{method:"POST",headers:{"Content-Type":"application/pdf"},body:row.pdf});const ur=await up.json();if(!up.ok)throw new Error(ur.error||"PDF 上傳失敗");}const sr=await fetch(`/api/jobs/${created.jobId}/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"all"})});const st=await sr.json();if(!sr.ok)throw new Error(st.error||"啟動寄送失敗");setMessage("批次寄送已開始…");for(let i=0;i<1200;i++){const snap=await(await fetch(`/api/jobs/${created.jobId}`)).json();if(snap.job?.status==="completed"){if(snap.job.failedCount===0){setMessage(`寄送完成：成功 ${snap.job.sentCount} 封。`);return;}throw new Error(`寄送完成，但有 ${snap.job.failedCount} 封失敗`);}await new Promise(r=>setTimeout(r,1000));}throw new Error("等待逾時，請稍後確認寄送狀態");}catch(e){setMessage(e instanceof Error?e.message:"寄送失敗");}finally{setBusy(false);}}

 return <>{mailReady===false&&<div className="setup-banner"><strong>Lark Mail 尚未連接</strong><span>請先完成 SMTP 環境變數設定。</span></div>}<section className="workflow-card"><div className="section-head"><div><p className="eyebrow">PART TWO</p><h2>批次 Mail 寄送</h2></div><span className="section-note">多份 PDF → 各自 Email</span></div><div className="upload-grid"><button className="dropzone" onClick={()=>pdfInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();takePdfs(e.dataTransfer.files)}}><input ref={pdfInput} type="file" multiple accept=".pdf,application/pdf" onChange={e=>takePdfs(e.target.files)}/><span className="upload-icon">PDF</span><strong>上傳全部已加密 PDF</strong><small>可一次選擇多份，不會再次加密</small><em>{pdfs.length?`已選擇 ${pdfs.length} 份 PDF`:"拖曳或點擊選擇"}</em></button><button className="dropzone" onClick={()=>excelInput.current?.click()}><input ref={excelInput} type="file" accept=".xlsx,.xls" onChange={e=>void takeExcel(e.target.files?.[0])}/><span className="upload-icon excel">XLS</span><strong>上傳寄送名單</strong><small>第一列包含「姓名、Email」</small><em>{excelName||"點擊選擇"}</em></button></div><div className="template-row"><span>{error||"依 PDF 檔名配對姓名與 Email"}</span><button onClick={template}>下載 Excel 範本</button></div></section>
 {rows.length>0&&<section className="results-card"><div className="section-head"><div><p className="eyebrow">MAIL REVIEW</p><h2>寄送配對結果</h2></div><div className="stats"><span><b>{rows.length}</b> 全部</span><span className="ok"><b>{summary.ready}</b> 可寄送</span><span className="warn"><b>{summary.problem}</b> 需處理</span></div></div><div className="table-wrap"><table><thead><tr><th>姓名</th><th>PDF 檔案</th><th>收件 Email</th><th>狀態</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}><td><strong>{r.name}</strong>{r.row>0&&<small>Excel 第 {r.row} 列</small>}</td><td><div className="pdf-file-line"><span>{r.pdf?.name||"—"}</span>{r.pdf&&<button className="remove-pdf-button" onClick={()=>remove(r)}>移除 PDF</button>}</div>{r.status==="invalid_filename"&&<label className="manual-match"><span>不用重傳，手動指定員工</span><select defaultValue="" onChange={e=>assign(r.key,Number(e.target.value))}><option value="" disabled>選擇 Excel 員工…</option>{people.map(p=>{const used=rows.some(x=>x.row===p.row&&x.pdf);return <option key={p.row} value={p.row} disabled={used}>{p.name}{used?"（已有 PDF）":""}</option>})}</select></label>}</td><td>{r.email||"—"}</td><td><span className={`badge ${r.status}`}>{labels[r.status]}</span>{r.manual&&<small className="manual-message">已手動配對</small>}{r.message&&<small className="row-message">{r.message}</small>}</td></tr>)}</tbody></table></div><div className="compose-grid"><label>郵件主旨模板<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>郵件內容模板<textarea value={body} onChange={e=>setBody(e.target.value)}/></label></div><div className="variable-help"><strong>可套用：</strong><code>{"{{name}}"}</code> 姓名　<code>{"{{email}}"}</code> Email　<code>{"{{filename}}"}</code> PDF 檔名</div><div className="send-panel"><div className="review-note"><strong>寄送前逐封預覽</strong><span>使用左右按鈕檢查全部郵件，預覽不會寄出。</span></div><div><p>{message||(summary.problem?"請先處理全部異常。":`共 ${summary.ready} 封等待預覽`)}</p><button className="send-button" disabled={!!summary.problem||!summary.ready||busy||mailReady!==true} onClick={openPreview}>{busy?"寄送中…":"下一步：預覽全部郵件"}</button></div></div></section>}
 {preview&&previewRow&&<div className="preview-overlay"><section className="preview-dialog"><div className="preview-head"><div><p className="eyebrow">EMAIL REVIEW</p><h2>預覽郵件內容</h2></div><div className="preview-count">第 <b>{previewIndex+1}</b> 封／共 {previewRows.length} 封</div></div><div className="preview-recipient"><span>收件人</span><strong>{previewRow.name}</strong><em>{previewRow.email}</em></div><div className="email-preview"><div className="email-line"><span>主旨</span><strong>{render(subject,previewRow)}</strong></div><div className="email-body">{render(body,previewRow)}</div><div className="attachment-chip"><span>PDF</span><div><strong>{previewRow.pdf?.name}</strong><small>只寄送至 {previewRow.email}</small></div></div></div><div className="preview-nav"><button className="secondary-button" disabled={previewIndex===0} onClick={()=>setPreviewIndex(i=>i-1)}>← 上一封</button><input type="range" min="1" max={previewRows.length} value={previewIndex+1} onChange={e=>setPreviewIndex(Number(e.target.value)-1)}/><button className="secondary-button" disabled={previewIndex===previewRows.length-1} onClick={()=>setPreviewIndex(i=>i+1)}>下一封 →</button></div><div className="preview-actions"><button className="text-button" onClick={()=>setPreview(false)}>返回修改</button><button className="send-button" disabled={busy} onClick={()=>void send()}>確認全部 {previewRows.length} 封並寄送</button></div><p className="preview-warning">按下後會正式批次寄出。</p></section></div>}</>;
}
