import { useEffect, useRef, useState } from "react";

export default function SingleMailTab(){
  const input=useRef<HTMLInputElement>(null); const [ready,setReady]=useState<boolean|null>(null),[pdf,setPdf]=useState<File|null>(null),[name,setName]=useState(""),[email,setEmail]=useState("");
  const [subject,setSubject]=useState("【個人文件】{{name}} 您的加密 PDF 文件"),[body,setBody]=useState("{{name}} 您好：\n\n附件是您的加密 PDF 文件，請使用約定的密碼開啟。\n\n如有問題，請聯絡相關承辦人員。\n謝謝"),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const valid=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()); useEffect(()=>{fetch("/api/config").then(r=>r.json()).then(v=>setReady(Boolean(v.larkReady))).catch(()=>setReady(false));},[]);
  const render=(text:string)=>text.replace(/{{\s*name\s*}}/gi,name.trim()||"您好").replace(/{{\s*email\s*}}/gi,email.trim()).replace(/{{\s*filename\s*}}/gi,pdf?.name||"");
  function take(file?:File){if(file?.name.toLowerCase().endsWith(".pdf")){setPdf(file);setMessage("");}}
  async function send(){if(!pdf||!valid||busy)return;setPreview(false);setBusy(true);try{setMessage("正在建立寄送任務…");const cr=await fetch("/api/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject,body,items:[{name:name.trim()||email.split("@")[0],email:email.trim(),filename:pdf.name}]})});const created=await cr.json();if(!cr.ok||!created.jobId||!created.items?.[0])throw new Error(created.error||"建立任務失敗");setMessage("正在上傳 PDF…");const up=await fetch(`/api/jobs/${created.jobId}/items/${created.items[0].itemId}/upload`,{method:"POST",headers:{"Content-Type":"application/pdf"},body:pdf});const ur=await up.json();if(!up.ok)throw new Error(ur.error||"上傳失敗");const sr=await fetch(`/api/jobs/${created.jobId}/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"all"})});const st=await sr.json();if(!sr.ok)throw new Error(st.error||"啟動寄送失敗");setMessage("已進入寄送佇列…");for(let i=0;i<120;i++){const snap=await(await fetch(`/api/jobs/${created.jobId}`)).json();if(snap.job?.status==="completed"){if(snap.job.sentCount===1){setMessage(`寄送成功：${email.trim()}`);setPdf(null);if(input.current)input.current.value="";return;}throw new Error(snap.items?.[0]?.error||"寄送失敗");}await new Promise(r=>setTimeout(r,1000));}throw new Error("等待逾時，請稍後確認寄送狀態");}catch(e){setMessage(e instanceof Error?e.message:"寄送失敗");}finally{setBusy(false);}}
  return <>{ready===false&&<div className="setup-banner"><strong>Lark Mail 尚未連接</strong><span>請先完成 SMTP 環境變數設定。</span></div>}<section className="workflow-card"><div className="section-head"><div><p className="eyebrow">PART TWO</p><h2>單封 Mail 寄送</h2></div><span className="section-note">1 PDF → 1 Email</span></div><div className="single-mail-grid"><button className="dropzone compact" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();take(e.dataTransfer.files[0])}}><input ref={input} type="file" accept=".pdf,application/pdf" onChange={e=>take(e.target.files?.[0])}/><span className="upload-icon">PDF</span><strong>選擇已加密 PDF</strong><small>這裡不會再次加密，請確認已有密碼</small><em>{pdf?.name||"拖曳或點擊選擇"}</em></button><div className="mail-fields"><label>收件人姓名（選填）<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：Sierra"/></label><label>收件 Email<input type="email" value={email} onChange={e=>{setEmail(e.target.value);setMessage("")}} placeholder="name@example.com"/><small>{email&&!valid?"Email 格式不正確":"只會寄到這一個信箱"}</small></label></div></div><div className="compose-grid"><label>郵件主旨<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>郵件內容<textarea value={body} onChange={e=>setBody(e.target.value)}/></label></div><div className="variable-help"><strong>可套用：</strong><code>{"{{name}}"}</code> 姓名　<code>{"{{email}}"}</code> Email　<code>{"{{filename}}"}</code> PDF 檔名</div><div className="send-panel"><div className="review-note"><strong>寄送前須預覽確認</strong><span>確認後只把這一份 PDF 寄到指定 Email。</span></div><div><p>{message||"請確認上傳的是已加密 PDF。"}</p><button className="send-button" disabled={!pdf||!valid||!subject.trim()||!body.trim()||busy||ready!==true} onClick={()=>setPreview(true)}>{busy?"寄送中…":"預覽這封郵件"}</button></div></div></section>{preview&&pdf&&<div className="preview-overlay"><section className="preview-dialog"><div className="preview-head"><div><p className="eyebrow">EMAIL REVIEW</p><h2>確認單封郵件</h2></div></div><div className="preview-recipient"><span>收件人</span><strong>{name.trim()||"未填姓名"}</strong><em>{email}</em></div><div className="email-preview"><div className="email-line"><span>主旨</span><strong>{render(subject)}</strong></div><div className="email-body">{render(body)}</div><div className="attachment-chip"><span>PDF</span><div><strong>{pdf.name}</strong><small>只寄送至 {email}</small></div></div></div><div className="preview-actions"><button className="text-button" onClick={()=>setPreview(false)}>返回修改</button><button className="send-button" disabled={busy} onClick={()=>void send()}>確認並寄送這一封</button></div><p className="preview-warning">按下後會正式寄出。</p></section></div>}</>;
}
